<?php

return [
    'cache_hours' => (int) env('ADSENSE_VALIDATOR_CACHE_HOURS', 6),
    'history_limit' => (int) env('ADSENSE_VALIDATOR_HISTORY_LIMIT', 20),
    'ready_score' => 90,
    'almost_ready_score' => 75,
    'weights' => [
        'trust' => 12,
        'content' => 17,
        'tool_quality' => 8,
        'blog_quality' => 7,
        'comparison_quality' => 6,
        'topic_quality' => 6,
        'technical_seo' => 12,
        'performance' => 8,
        'accessibility' => 7,
        'mobile' => 5,
        'internal_linking' => 6,
        'policy_compliance' => 6,
    ],
    'quality_signals' => [
        'tool' => [
            'introduction', 'tool_interface', 'how_to', 'examples', 'advantages',
            'limitations', 'best_practices', 'common_mistakes', 'faq',
            'related_tools', 'related_articles', 'official_references', 'feedback',
        ],
        'blog' => [
            'summary', 'table_of_contents', 'examples', 'author', 'reviewer',
            'official_references', 'faq', 'feedback', 'related_tools', 'related_articles',
        ],
        'comparison' => [
            'winner_summary', 'comparison_table', 'decision_guidance', 'examples',
            'pros_cons', 'faq', 'official_references', 'related_tools', 'related_articles',
        ],
        'topic' => [
            'overview', 'featured_tools', 'popular_articles', 'comparisons',
            'glossary', 'beginner_guide', 'faq', 'related_tools',
        ],
        'category' => [
            'overview', 'featured_tools', 'popular_articles', 'comparisons',
            'glossary', 'beginner_guide', 'faq', 'related_tools',
        ],
    ],
    'signal_labels' => [
        'introduction' => 'Original introduction',
        'tool_interface' => 'Working tool interface',
        'how_to' => 'How To Use section',
        'examples' => 'Practical examples',
        'formula' => 'Formula where applicable',
        'advantages' => 'Advantages or benefits',
        'limitations' => 'Honest limitations',
        'best_practices' => 'Best practices',
        'common_mistakes' => 'Common mistakes',
        'faq' => 'Frequently asked questions',
        'related_tools' => 'Related tools',
        'related_articles' => 'Related articles',
        'related_comparisons' => 'Related comparisons',
        'topic_links' => 'Topic links',
        'official_references' => 'Official references',
        'feedback' => 'User feedback control',
        'summary' => 'Article summary',
        'table_of_contents' => 'Table of contents',
        'author' => 'Author attribution',
        'reviewer' => 'Reviewer attribution',
        'winner_summary' => 'Quick winner summary',
        'comparison_table' => 'Feature comparison table',
        'decision_guidance' => 'Decision guidance',
        'pros_cons' => 'Advantages and disadvantages',
        'overview' => 'Topic overview',
        'featured_tools' => 'Featured tools',
        'popular_articles' => 'Popular articles',
        'comparisons' => 'Comparison pages',
        'glossary' => 'Glossary',
        'beginner_guide' => 'Beginner guide',
    ],
];
