<?php

return [
    'topics' => [
        'image-tools' => [
            'title' => 'Image Tools', 'category' => 'Image Tools',
            'description' => 'A complete guide to creating, resizing, compressing, converting and preparing digital images.',
            'audience' => ['designers', 'developers', 'online sellers', 'content creators', 'students and everyday users'],
            'outcomes' => ['smaller downloads', 'consistent dimensions', 'cleaner visual output', 'compatible file formats', 'faster websites'],
            'workflows' => ['optimizing website photographs', 'preparing transparent logos', 'resizing marketplace images', 'converting files for compatible software', 'extracting colors from a source image'],
            'concepts' => ['dimensions and aspect ratio', 'lossy and lossless compression', 'raster and vector graphics', 'color and transparency', 'file-format compatibility'],
            'examples' => ['compressing a product photograph before upload', 'turning a transparent PNG into a smaller web asset', 'resizing a profile image without distortion'],
            'best_practices' => ['Keep an untouched original before editing or conversion.', 'Choose dimensions for the actual display context instead of uploading oversized files.', 'Use lossless formats for sharp graphics and transparency, and efficient lossy formats for photographs.', 'Preview compressed output at normal viewing size before downloading.', 'Use descriptive filenames and meaningful alternative text when publishing images online.', 'Check color, transparency and metadata requirements at the final destination.'],
            'mistakes' => ['Stretching an image without preserving its aspect ratio.', 'Repeatedly saving a lossy file and accumulating artifacts.', 'Choosing PNG for every photograph regardless of file size.', 'Removing transparency by converting to a format that does not support it.', 'Uploading sensitive image metadata without reviewing it.', 'Assuming a larger pixel count always creates visibly better output.'],
            'glossary' => ['PNG' => 'A lossless raster format with alpha transparency.', 'JPEG' => 'A widely compatible lossy format commonly used for photographs.', 'WebP' => 'A modern format supporting efficient lossy, lossless and transparent images.', 'DPI' => 'Dots per inch, commonly used when discussing print output density.', 'Compression' => 'A method of reducing file size, either with or without information loss.', 'Transparency' => 'Image areas that allow content behind the image to remain visible.', 'Aspect ratio' => 'The proportional relationship between image width and height.', 'Raster' => 'An image represented as a grid of pixels.'],
        ],
        'pdf-tools' => [
            'title' => 'PDF Tools', 'category' => 'PDF Tools',
            'description' => 'Learn how to create, combine, split, compress and organize portable document files efficiently.',
            'audience' => ['students', 'office teams', 'teachers', 'freelancers', 'administrators and small businesses'],
            'outcomes' => ['organized documents', 'smaller attachments', 'clean page sequences', 'portable sharing', 'simpler submission workflows'],
            'workflows' => ['combining reports into one file', 'extracting selected pages', 'preparing documents for an upload limit', 'turning images into a PDF', 'reordering pages before delivery'],
            'concepts' => ['pages and page ranges', 'compression and image quality', 'document metadata', 'password protection', 'digital and scanned PDFs'],
            'examples' => ['merging multiple invoices for one submission', 'splitting one chapter from a large handbook', 'compressing a scanned form before emailing it'],
            'best_practices' => ['Keep the original document before merging, splitting or compression.', 'Confirm page order and orientation before sharing the final file.', 'Use an appropriate compression level for text, diagrams and scanned photographs.', 'Review confidential pages and metadata before uploading or sending a document.', 'Give the output a descriptive filename and confirm it opens correctly.', 'Use password protection only with a secure method for sharing the password.'],
            'mistakes' => ['Compressing a document so heavily that small text becomes unreadable.', 'Merging documents without checking page order.', 'Assuming a scanned PDF contains selectable text.', 'Sharing confidential metadata or hidden pages.', 'Using unclear filenames for final submissions.', 'Deleting originals before verifying the processed file.'],
            'glossary' => ['PDF' => 'Portable Document Format, designed to preserve document layout.', 'Page range' => 'A selected sequence of pages such as 2–5 or 1, 4 and 8.', 'OCR' => 'Optical character recognition used to turn scanned text into searchable text.', 'Compression' => 'Reduction of document file size, often by optimizing embedded images.', 'Metadata' => 'Document information such as title, author and creation software.', 'Encryption' => 'Protection that restricts access without the correct password or key.', 'Merge' => 'Combining multiple PDF documents into one file.', 'Split' => 'Separating a PDF into smaller documents or individual pages.'],
        ],
        'finance-tools' => [
            'title' => 'Finance Tools', 'category' => 'Finance',
            'description' => 'Understand financial calculators for loans, taxes, savings, investments and everyday planning.',
            'audience' => ['households', 'borrowers', 'savers', 'investors', 'students and small-business owners'],
            'outcomes' => ['clearer estimates', 'better scenario comparisons', 'fewer formula errors', 'more realistic goals', 'informed financial conversations'],
            'workflows' => ['estimating loan instalments', 'calculating GST', 'projecting recurring investments', 'comparing deposit growth', 'reviewing interest and inflation'],
            'concepts' => ['principal and interest', 'compounding', 'rates and time periods', 'cash flow', 'risk and return'],
            'examples' => ['comparing two loan tenures before applying', 'estimating the future value of monthly investments', 'checking tax added to a base price'],
            'best_practices' => ['Use realistic rates, time periods and contribution amounts.', 'Compare more than one scenario instead of relying on a single estimate.', 'Keep annual and monthly rates or periods consistent.', 'Include fees, taxes and inflation when they materially affect the decision.', 'Verify current official rules and provider terms.', 'Treat calculator output as planning information rather than personal financial advice.'],
            'mistakes' => ['Mixing monthly and annual interest rates.', 'Ignoring processing fees, taxes or early-exit penalties.', 'Assuming market-linked returns are guaranteed.', 'Comparing products with different time horizons.', 'Entering percentages as decimal values in the wrong field.', 'Making an important decision from one estimate without verification.'],
            'glossary' => ['Principal' => 'The original amount borrowed, deposited or invested.', 'Interest' => 'The cost of borrowing or return paid on eligible savings.', 'EMI' => 'An equated monthly instalment used to repay a loan.', 'Compounding' => 'Earning or charging returns on previous accumulated amounts.', 'APR' => 'An annualized measure of borrowing cost where applicable.', 'Inflation' => 'The general increase in prices that reduces purchasing power.', 'Liquidity' => 'How easily an asset can be converted into spendable money.', 'Risk' => 'The possibility that actual outcomes differ from expected outcomes.'],
        ],
        'developer-tools' => [
            'title' => 'Developer Tools', 'category' => 'Developer Tools',
            'description' => 'A practical guide to formatting, validating, converting and inspecting data used in software development.',
            'audience' => ['software developers', 'QA engineers', 'students', 'API teams', 'technical writers and support engineers'],
            'outcomes' => ['readable payloads', 'faster debugging', 'valid test data', 'consistent transformations', 'less context switching'],
            'workflows' => ['formatting API responses', 'validating JSON', 'parsing URLs', 'generating identifiers', 'encoding or decoding test values'],
            'concepts' => ['structured data', 'encoding and hashing', 'validation', 'syntax and formatting', 'browser-local processing'],
            'examples' => ['beautifying an unreadable JSON response', 'checking whether a callback URL contains the expected parameters', 'generating UUIDs for test fixtures'],
            'best_practices' => ['Work with sanitized samples instead of production secrets.', 'Validate data before transforming or sharing it.', 'Preserve the original input when debugging conversions.', 'Confirm character encoding at system boundaries.', 'Use cryptographic functions only for their documented purpose.', 'Add automated validation to production workflows even when browser tools help during investigation.'],
            'mistakes' => ['Pasting credentials or private production data into unnecessary tools.', 'Confusing encoding, encryption and hashing.', 'Formatting invalid data without first reading the parser error.', 'Assuming converted structures preserve every format-specific feature.', 'Using a UUID or random string as a security control by itself.', 'Testing only one happy-path payload.'],
            'glossary' => ['JSON' => 'A lightweight data format using objects, arrays and primitive values.', 'XML' => 'An extensible markup format for structured data and documents.', 'API' => 'An interface that allows software systems to exchange requests and responses.', 'Base64' => 'A text encoding for representing binary bytes; it is not encryption.', 'Hash' => 'A fixed-length digest produced from input data.', 'UUID' => 'A standardized identifier designed to be broadly unique.', 'Validation' => 'Checking data against syntax or business requirements.', 'URL' => 'A uniform resource locator identifying a resource and access scheme.'],
        ],
        'seo-tools' => [
            'title' => 'SEO Tools', 'category' => 'SEO Tools',
            'description' => 'Learn the technical and content foundations used to make websites discoverable and understandable in search.',
            'audience' => ['SEO specialists', 'content writers', 'developers', 'bloggers', 'agencies and website owners'],
            'outcomes' => ['cleaner metadata', 'stronger crawl discovery', 'consistent URLs', 'better content reviews', 'clear social previews'],
            'workflows' => ['creating meta tags', 'reviewing keyword usage', 'generating sitemaps', 'preparing robots rules', 'building clean URL slugs'],
            'concepts' => ['crawlability and indexing', 'metadata', 'search intent', 'internal linking', 'structured page discovery'],
            'examples' => ['checking a draft for repeated keywords', 'creating a sitemap for a small site', 'generating consistent slugs for new articles'],
            'best_practices' => ['Write metadata for people while accurately describing the page.', 'Keep important pages reachable through contextual internal links.', 'Maintain sitemaps as content is added or removed.', 'Use robots directives carefully and verify their scope.', 'Review content quality and intent instead of chasing a fixed keyword percentage.', 'Measure results over time and update pages when information changes.'],
            'mistakes' => ['Stuffing keywords into text or metadata unnaturally.', 'Blocking important resources or pages in robots rules.', 'Submitting stale or invalid sitemap URLs.', 'Using identical titles and descriptions across many pages.', 'Creating slugs that are long, unclear or inconsistent.', 'Treating one automated check as a complete SEO strategy.'],
            'glossary' => ['SEO' => 'Search engine optimization: improving discoverability and search usefulness.', 'Crawl' => 'The process of discovering and requesting web pages.', 'Index' => 'A search engine collection of understood pages eligible for retrieval.', 'Meta description' => 'A page summary that may be used in search snippets.', 'Canonical URL' => 'The preferred URL representing a page among duplicates or variants.', 'Sitemap' => 'A machine-readable list of important website URLs.', 'Robots directive' => 'An instruction affecting crawler access or page indexing.', 'Slug' => 'The readable URL segment identifying a page.'],
        ],
        'text-tools' => [
            'title' => 'Text Tools', 'category' => 'Text Tools',
            'description' => 'A comprehensive guide to writing, counting, cleaning, transforming and organizing text efficiently.',
            'audience' => ['writers', 'students', 'editors', 'marketers', 'researchers and developers'],
            'outcomes' => ['cleaner drafts', 'consistent formatting', 'accurate counts', 'organized lists', 'copy-ready output'],
            'workflows' => ['changing letter case', 'counting words and characters', 'removing duplicate lines', 'sorting lists', 'cleaning copied whitespace'],
            'concepts' => ['characters and words', 'case and capitalization', 'whitespace', 'line-based data', 'encoding and transformation'],
            'examples' => ['cleaning a keyword export before a spreadsheet import', 'checking an essay against a word limit', 'normalizing headings into consistent title case'],
            'best_practices' => ['Keep an original copy before applying bulk transformations.', 'Review capitalization rules for names and specialist terms.', 'Confirm whether matching should be case-sensitive.', 'Use line-based tools only when each row represents a separate item.', 'Check character limits at the final publishing destination.', 'Read the transformed output once before copying it into production content.'],
            'mistakes' => ['Applying title case to acronyms and proper names without review.', 'Removing duplicate lines when repeated values are meaningful.', 'Counting pasted formatting characters as visible content.', 'Sorting numbered items alphabetically instead of numerically.', 'Losing paragraph breaks during whitespace cleanup.', 'Assuming encoded text is encrypted or protected.'],
            'glossary' => ['Character' => 'A letter, number, symbol, punctuation mark or whitespace unit.', 'Word count' => 'The number of detected word tokens in a text.', 'Whitespace' => 'Spaces, tabs, line breaks and similar separating characters.', 'Case' => 'The uppercase or lowercase form of letters.', 'Duplicate' => 'A repeated value identified under chosen matching rules.', 'Delimiter' => 'A character used to separate values or fields.', 'Encoding' => 'A convention for representing text or bytes.', 'Slug' => 'A lowercase, hyphen-separated phrase commonly used in URLs.'],
        ],
    ],
];
